### ISSUE TITLE
Add audit logging

### ISSUE THREAD

**Issue by codemicro** [CSSUoB/society-voting#19]
Because it'd be nice to know why users go missing if they go missing 

Blocked on #20

**Comment by sapphyree** [comment]
How extensive is this logging? Is it just the base audit system Discord has? Any form of permanent logging should be communicated to the members of the server and they should be informed of any logging to their activity when they join.

**Comment by MattyTheHacker** [comment]
this is for the voting site, not Discord so isn't relevant to be informed when they join the server. My understanding as well is this is specifically audit in relation to administrative actions being taken
